FROM dp.apps.rancher.io/containers/go:1.25.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -trimpath -o /app/genaisync ./cmd/sync/main.go

FROM dp.apps.rancher.io/containers/bci-micro:15.7

USER 1001
WORKDIR /app

COPY --from=builder /app/genaisync .

CMD ["/app/genaisync"]
