FROM opensuse/tumbleweed

RUN curl -o- https://dl.stackstate.com/stackstate-cli/install.sh | bash
COPY setup/stackpack    /mnt/.
COPY setup/deps    /mnt/.
COPY setup/init.sh /mnt/.

ENTRYPOINT ["/bin/bash", "/mnt/init.sh"]
