FROM opensuse/tumbleweed
RUN zypper --non-interactive refresh && \
    zypper --non-interactive install jq
RUN curl -o- https://dl.stackstate.com/stackstate-cli/install.sh | bash
COPY setup/stackpack    /mnt/.
COPY setup/deps    /mnt/.
COPY setup/init.sh /mnt/.

ENTRYPOINT ["/bin/bash", "/mnt/init.sh"]
