version: '3'

dotenv: ['./.env']

vars:
  IMAGE: "genai-observability"
  VERSION: 0.0.1

tasks:
  docker-build-runtime:
    cmds:
      - docker build -f Dockerfile.runtime -t {{.IMAGE}}-runtime:{{.VERSION}} .
  docker-build-setup:
    cmds:
      - docker build -f Dockerfile.setup -t {{.IMAGE}}-setup:{{.VERSION}} .
