version: '3'

dotenv: ['./.env']

vars:
  IMAGE: "ghcr.io/thbertoldi/genai-observability"
  VERSION: latest

tasks:
  docker-build-runtime:
    cmds:
      - docker build -f Dockerfile.runtime -t {{.IMAGE}}-runtime:{{.VERSION}} .
  docker-build-setup:
    cmds:
      - docker build -f Dockerfile.setup -t {{.IMAGE}}-setup:{{.VERSION}} .
  push-images:
    cmds:
      - docker push {{.IMAGE}}-runtime:{{.VERSION}}
      - docker push {{.IMAGE}}-setup:{{.VERSION}}
