version: '3'

dotenv: ['./.env']

vars:
  IMAGE: "genai-observability"
  VERSION: latest

tasks:
  podman-build-runtime:
    cmds:
      - podman build -f Dockerfile.runtime -t {{.IMAGE}}-runtime:{{.VERSION}} .
  podman-build-setup:
    cmds:
      - podman build -f Dockerfile.setup -t {{.IMAGE}}-setup:{{.VERSION}} .
  push-images:
    cmds:
      - podman push {{.IMAGE}}-runtime:{{.VERSION}}
      - podman push {{.IMAGE}}-setup:{{.VERSION}}

  version-up:
    desc: Increments the stackpack version (patch)
    cmds:
      - |
        VERSION=$(grep 'version =' stackpack/suse-ai/stackpack.conf | cut -d'"' -f2)
        BASE=$(echo $VERSION | cut -d'.' -f1-2)
        PATCH=$(echo $VERSION | cut -d'.' -f3)
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$BASE.$NEW_PATCH"
        sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" stackpack/suse-ai/stackpack.conf
        echo "StackPack version updated to $NEW_VERSION"

  stackpack-upload:
    desc: Zips, uploads and upgrades the stackpack
    cmds:
      - |
        cd stackpack/suse-ai
        zip -r /tmp/suse-ai.sts stackpack.conf provisioning resources
        sts stackpack upload --file /tmp/suse-ai.sts
        sts stackpack upgrade --name suse-ai --unlocked-strategy overwrite

  stackpack-uninstall:
    desc: Uninstall all installed instances of SUSE AI Observability stackpack
    cmds:
      - |
        sts stackpack list-instances --name suse-ai -o json | jq -r '.instances[] | select(.status == "INSTALLED" or .status == "ERROR") | .id' | while read ID; do
          echo "Uninstalling instance $ID"
          sts stackpack uninstall --id "$ID" --name suse-ai
        done

  sts-script:
    desc: Runs a Groovy script from a file (use FILE=path/to/script.groovy)
    cmds:
      - sts script run --file "{{.FILE}}"
