#!/bin/bash
sts stackpack upload --file /mnt/autosync-3.2.1-stac-0-bump-1037-203fef5-SNAPSHOT.sts --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts stackpack install -n autosync -p sts_instance_type=openlit -p sts_instance_url="$KUBERNETES_CLUSTER" --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/menu/llm.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/overview/genai_system.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/overview/gpu_nodes.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/overview/vector_db_system.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/overview/genai_apps.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/components/genai_system_ollama.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/components/genai_system_openai.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/components/genai_dbsystem_milvus.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/metrics/gpu_nodes.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/metrics/gpu_pods.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/metrics/genai_systems.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/metrics/db_systems.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts settings apply -f /mnt/metrics/genai_apps.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
sts monitor apply -f /mnt/monitors/monitors.yaml --url "$STACKSTATE_API_URL" --api-token "$STACKSTATE_API_TOKEN"
